### ISSUE TITLE
如何获取操作来源的ip呢

### ISSUE THREAD

**Issue by jiashiwen** [leonchen83/redis-replicator#24]
您好，假设在双向复制的场景中，如何能够得到事件动作的来源ip呢。从而破掉循环动作？

**Comment by leonchen83** [comment]
这个工作不由redis-replicator来做， redis-replicator也没办法获得数据来源
一个可行的方案是设计良好的key-value结构来包含来源， 比如一个string类型的key value数据，可以存储如下的value结构
`{"value": "your value", "source" : "192,168.1.104", "timestamp":1531183254655}`, 这样在同步的时候获得这个value里的ip的话，可以打破循环， 但实际上， 双向同步还有其他的很多问题， 最好是主备方式而不是双向同步

**Comment by jiashiwen** [comment]
多谢了
