### ISSUE TITLE
如果在源redis配置了password，replicator中如何进行密码验证

### ISSUE THREAD

**Issue by jiashiwen** [leonchen83/redis-replicator#25]
如果在源redis配置了password，replicator中如何进行密码验证？例子中有目的地址的验证方法，不知道源中password如何解析到replicator中

**Comment by leonchen83** [comment]
参照[redis 认证](https://github.com/leonchen83/redis-replicator/blob/master/README.zh_CN.md#55-redis%E8%AE%A4%E8%AF%81)  
简单来说就是在redis的uri中指定auth password 如下所示  
`redis://127.0.0.1:6379?authPassword=yourpassword` 注意大小写

**Comment by jiashiwen** [comment]
多谢指导
