### ISSUE TITLE
redis-replicator如何添加key过期时间和LFU、LRU信息

### ISSUE THREAD

**Issue by vinllen** [leonchen83/redis-replicator#28]
请教一下，replicator全量rdb同步是采用什么机制的？挨个entry解析然后写入目的redis吗？如果是的话，如何处理key的过期时间、5.0添加的LFU以及LRU信息？redis本身好像不支持单个key的LFU、LRU信息的配置，key过期时间是采用同步key+expire2条命令实现的吗？

**Comment by leonchen83** [comment]
感谢提出issue
1. replicator全量rdb同步是采用什么机制的？
replicator会把rdb文件解析回一个一个key value， 然后根据不通的`RdbVisitor`可以做不同的处理， 比如`DumpRdbVisitor`会把rdb文件解析成redis的dump格式， 然后通过`restore` 命令迁移到目标redis

2. 如何处理key的过期时间、5.0添加的LFU以及LRU信息？
在解析rdb的过程中， 如果rdb的key是带有过期时间的，那么是可以得到这个过期时间， 通过以下方法
`KeyValuePair.getExpiredType`和 `KeyValuePair.getExpiredValue`
5.0 LFU 以及LRU信息也可以得到， 通过以下方法
`KeyValuePair.getEvictType`和 `KeyValuePair.getEvictValue`

**Comment by vinllen** [comment]
感谢回答
