### ISSUE TITLE
定时同步支持吗？

### ISSUE THREAD

**Issue by mrvon2015** [leonchen83/redis-replicator#29]
redis定时同步到mysql，支持吗？我看到都是redis有变动，实时监听之后同步到mysql。能不能做定时同步，自定义同步的时间？

**Comment by leonchen83** [comment]
see [https://github.com/leonchen83/redis-replicator/blob/master/examples/com/moilioncircle/examples/other/TimerTaskExample.java](TimerTaskExample)
但是一些逻辑代码以及业务还需要自己扩展

**Comment by mrvon2015** [comment]
感谢了
