### ISSUE TITLE
redis定时同步到mysql，RDB和AOF哪种更适合？

### ISSUE THREAD

**Issue by mrvon2015** [leonchen83/redis-replicator#30]
请教个问题：
使用场景是：数据写入和读取都是在redis，然后使用redis-replicator定时同步到mysql。
redis-replicator里面有2种同步方式，请问哪种更适合？

**Comment by leonchen83** [comment]
实时性要求不高的话可以定时分析rdb， 实时性要求高的话， 可以rdb+aof结合着来
redis的同步机制是先发送rdb,然后持续发送aof， 但是这种同步有一定要求， 就是同步到mysql的速度要快， 不能积压太多的event

**Comment by mrvon2015** [comment]
多谢哈
