### ISSUE TITLE
支持双向同步么？

### ISSUE THREAD

**Issue by zhaizhifen** [leonchen83/redis-replicator#32]
支持双向同步么？

**Comment by vinllen** [comment]
需要依赖内核gid，阿里云云上是可以的，开源的目前没有这个gid。细节可以看下云栖上面的文档

**Comment by leonchen83** [comment]
双向同步不支持， 这只是一个同步协议的框架
如果有双向同步的需求，可以看看阿里开发的[RedisShake](https://github.com/alibaba/RedisShake)
