### ISSUE TITLE
扫rdb的时候 可以方便的获得KEY  占用了多少空间吗

### ISSUE THREAD

**Issue by noasoso** [leonchen83/redis-replicator#33]
扫rdb的时候 可以方便的获得KEY  占用了多少空间吗,
想汇总分析一下 key 占用空间情况

**Comment by leonchen83** [comment]
@noasoso 
这个需要在replicator外部做，可以参考[redis-rdb-tools](https://github.com/sripathikrishnan/redis-rdb-tools)或者[redis-rdb-cli](https://github.com/leonchen83/redis-rdb-cli)的计算方式把key占用的空间计算出来
