### ISSUE TITLE
使用疑问

### ISSUE THREAD

**Issue by copyshop** [leonchen83/redis-replicator#35]
目前两个redis-cluster集群需要两个集群做数据同步， 集群master a b c 集群master d e f,
怎么使用，我看到代码里面是RedisURI uri = new RedisURI(str);  只能是单机，集群怎么设置。

**Comment by leonchen83** [comment]
redis-replicator实现的是redis的replication协议， replication协议只支持点对点同步，所以redis-replicator也只支持点对点同步，如果想支持集群的话，需要自己写扩展，比如定期读取cluster info，然后建立多个replicator同步

**Comment by copyshop** [comment]
> redis-replicator实现的是redis的replication协议， replication协议只支持点对点同步，所以redis-replicator也只支持点对点同步，如果想支持集群的话，需要自己写扩展，比如定期读取cluster info，然后建立多个replicator同步

了解了，谢谢。
