### ISSUE TITLE
HSet命令需要支持多对field-value

### ISSUE THREAD

**Issue by maplestoria** [leonchen83/redis-replicator#38]
[Redis官网的描述](https://redis.io/commands/hset)：
![捕获](https://user-images.githubusercontent.com/25701092/92193794-c1622e00-ee9b-11ea-9ba5-8f2bfb1a30af.PNG)

---

HSetCommand.java中：

![捕获2](https://user-images.githubusercontent.com/25701092/92193797-c4f5b500-ee9b-11ea-815b-104d8f0333a7.PNG)

**Comment by leonchen83** [comment]
will fix at version 3.4.1

**Comment by leonchen83** [comment]
@maplestoria 
Fixed
```
<dependency>
  <groupId>com.moilioncircle</groupId>
  <artifactId>redis-replicator</artifactId>
  <version>3.4.2</version>
</dependency>
```

**Comment by maplestoria** [comment]
thanks
