### ISSUE TITLE
从一个clusterA的slaveA同步到另一个clusterB的masterB，如果slaveA或者masterB挂了的话，怎么实现故障转移和断点续传

### ISSUE THREAD

**Issue by lijiawen** [leonchen83/redis-replicator#39]

**Comment by leonchen83** [comment]
断点续传参考[FailoverExample.java](https://github.com/leonchen83/redis-replicator/blob/master/examples/com/moilioncircle/examples/failover/FailoverExample.java)
可以传入replId与replOffset。故障转移需要自己来做，比如定时ping cluster的机器，确保slaveA挂了连接masterA，目标端也是一样

**Comment by lijiawen** [comment]
好的，多谢

**Comment by lijiawen** [comment]
@leonchen83 ，再请教一个问题，redis异地同步的时候，由于网络等原因可能会出现全量同步的情况，是否可以通过replicator改造，避免全量同步的情况出现？能否提供一个思路，多谢！

**Comment by leonchen83** [comment]
这个是可以做到的，可以把replicator部署到离源端近的机房，这样replicator重连的时候，绝大部分可能会走增量同步，可以让replicator把同步数据保存到文件，然后慢慢同步到远端。

**Comment by leonchen83** [comment]
closed issue if no question
