### ISSUE TITLE
扫描RDB文件时如何获取Redis内存信息

### ISSUE THREAD

**Issue by ReasonDuan** [leonchen83/redis-replicator#42]
以前使用2.0版本时可以通过如下方式获得Redis 内存使用情况：
```java
			replicator.addAuxFieldListener(new AuxFieldListener() {
				@Override
				public void handle(Replicator replicator, AuxField auxField) {
					String auxKey = auxField.getAuxKey();
					if (used_mem_flag.equalsIgnoreCase(auxKey)) {
						Long used_mem = Long.parseLong(auxField.getAuxValue());
						AppCache.redisUsedMems.add(used_mem);
					}

				}
			});
```
3.0 后如何获取此信息？

**Comment by leonchen83** [comment]
```
replicator.addEventListener(new EventListener() {
            @Override
            public void onEvent(Replicator replicator, Event event) {
                if (event instanceof AuxField) {
                    AuxField aux = (AuxField)event;
                    System.out.println(aux.getAuxKey());
                    System.out.println(aux.getAuxValue());
                }
            }
        });
```

**Comment by ReasonDuan** [comment]
> ```
> replicator.addEventListener(new EventListener() {
>             @Override
>             public void onEvent(Replicator replicator, Event event) {
>                 if (event instanceof AuxField) {
>                     AuxField aux = (AuxField)event;
>                     System.out.println(aux.getAuxKey());
>                     System.out.println(aux.getAuxValue());
>                 }
>             }
>         });
> ```

好像不兼容3.0版本，4.0之后的没有问题

**Comment by leonchen83** [comment]
@ReasonDuan 
这个AuxField事件是redis3.2开始加上的

**Comment by ReasonDuan** [comment]
> @ReasonDuan
> 这个AuxField事件是redis3.2开始加上的

好的，谢谢
