### ISSUE TITLE
3.4.4版本的maven下载不下来

### ISSUE THREAD

**Issue by xiaozhiliaoo** [leonchen83/redis-replicator#43]
我在普通java项目里面引入pom文件，3.4.4版本的下载不到本地，3.4.3可以下载到本地
我用的这个里面的：https://mvnrepository.com/artifact/com.moilioncircle/redis-replicator/3.4.4

**Comment by leonchen83** [comment]
`wget https://search.maven.org/remotecontent?filepath=com/moilioncircle/redis-replicator/3.4.4/redis-replicator-3.4.4.jar`

**Comment by xiaozhiliaoo** [comment]
@leonchen83  好的，非常感谢，我现在用的3.4.3的啦
