### ISSUE TITLE
解析hash dump的值发生报错java.lang.AssertionError: unexpected value type:92

### ISSUE THREAD

**Issue by xiaozhiliaoo** [leonchen83/redis-replicator#44]
我用redis客户端创建一个hash，然后dump key的值，然后将dump的字符串放在代码中解析，总是报错 java.lang.AssertionError: unexpected value type:92，不知道为什么？感觉自己使用错了，但是没找到原因
复现步骤：
环境：redis单机
操作：step1：HSET myhash field1 "Hello"
           step2：DUMP myhash
生成dump值："\r\x1a\x1a\x00\x00\x00\x12\x00\x00\x00\x02\x00\x00\x06field1\b\x05Hello\xff\x06\x00DC\x19\t\xf9\x8c\xde`"
然后我把dump的值用replicator解析：

String fieldValue = "\\r\\x1a\\x1a\\x00\\x00\\x00\\x12\\x00\\x00\\x00\\x02\\x00\\x00\\x06field1\\b\\" +
                "x05Hello\\xff\\x06\\x00DC\\x19\\t\\xf9\\x8c\\xde`";
DumpValueParser parser = new DefaultDumpValueParser(new RedisReplicator("redis://127.0.0.1:6379"));
DumpKeyValuePair dkv = new DumpKeyValuePair();
dkv.setValue(fieldValue.getBytes());
KeyStringValueHash kv = (KeyStringValueHash) parser.parse(dkv);
return kv.getValue();

然后报错：java.lang.AssertionError: unexpected value type:92

	at com.moilioncircle.redis.replicator.rdb.dump.parser.DefaultDumpValueParser.parse(DefaultDumpValueParser.java:104)
	at com.chainup.cache.redis.core.RedisDumpParser.parseHash(RedisDumpParser.java:61)

帮忙看一下，非常感谢

**Comment by leonchen83** [comment]
```
        Replicator replicator = new RedisReplicator("redis://127.0.0.1:6379");
        DumpValueParser parser = new DefaultDumpValueParser(replicator);
        DumpKeyValuePair dkv = new DumpKeyValuePair();
        byte[] bytes = "\\r\\x1a\\x1a\\x00\\x00\\x00\\x12\\x00\\x00\\x00\\x02\\x00\\x00\\x06field1\\b\\x05Hello\\xff\\x06\\x00DC\\x19\\t\\xf9\\x8c\\xde`".getBytes();
        RedisCodec codec = new RedisCodec();
    
        dkv.setValue(codec.decode(bytes));
        KeyStringValueHash kv = (KeyStringValueHash)parser.parse(dkv);
        Map<byte[], byte[]> map = kv.getValue();
        for (Map.Entry<byte[], byte[]> entry : map.entrySet()) {
            System.out.println(new String(entry.getKey()));
            System.out.println(new String(entry.getValue()));
        }
```

**Comment by leonchen83** [comment]
raw dump data need to `decode` by `RedisCodec`

**Comment by xiaozhiliaoo** [comment]
@leonchen83  非常感谢

**Comment by xiaozhiliaoo** [comment]
@leonchen83  我还有一个疑问，为什么我直接通过jedis api从redis dump下来数据，可以不用RedisCodec就可以解析了？

**Comment by leonchen83** [comment]
因为二进制是不可打印的，会乱码。所以redis官方客户端输出dump的时候对不可打印字符做了16进制转义。jedis没做转义

**Comment by xiaozhiliaoo** [comment]
> 因为二进制是不可打印的，会乱码。所以redis官方客户端输出dump的时候对不可打印字符做了16进制转义。jedis没做转义

好的，非常感谢
