### ISSUE TITLE
目前支持的redis的版本

### ISSUE THREAD

**Issue by luwave** [leonchen83/redis-replicator#47]
发现拉取Redis version 2.8.23有解析报错

**Comment by leonchen83** [comment]
什么错误，有堆栈或者Log吗？

**Comment by luwave** [comment]
![image](https://user-images.githubusercontent.com/12522305/103348134-17568380-4ad4-11eb-821e-3655b4038da5.png)

**Comment by luwave** [comment]
![image](https://user-images.githubusercontent.com/12522305/103348159-263d3600-4ad4-11eb-8f42-352cc26bacb1.png)
![image](https://user-images.githubusercontent.com/12522305/103348203-4836b880-4ad4-11eb-893b-68e6b8e70caa.png)

**Comment by luwave** [comment]
redis里面存储的都是以byte[] 存储的序列化的对象

**Comment by leonchen83** [comment]
能提供出错的rdb吗

**Comment by luwave** [comment]
这个不能提供，抄到了原因，不是解析的问题，是源端生成rdb的时候，会出现错误的信息导致解析失败，但是不确定为什么会产生这样的问题
