### ISSUE TITLE
how to use redis aof log parser

### ISSUE THREAD

**Issue by dnlixiaoxin** [leonchen83/redis-replicator#54]
thanks

**Comment by leonchen83** [comment]
see [AofReadExample](https://github.com/leonchen83/redis-replicator/blob/master/examples/com/moilioncircle/examples/file/AofReadExample.java)

**Comment by dnlixiaoxin** [comment]
i want to use parser listen redis aof log changes and parser it, can redis-replicator support it?

**Comment by leonchen83** [comment]
yes
before redis 7.0, you have 2 methods to ignore rdb stream.

method 1.
you can set `Configuration.setDiscardRdbEvent(true)` to discard rdb event 
```
final Replicator replicator = new RedisReplicator("redis://127.0.0.1:6379?discardRdbEvent=yes");
        replicator.addEventListener(new EventListener() {
            @Override
            public void onEvent(Replicator replicator, Event event) {
                System.out.println(event);
            }
        });

        replicator.open();
```
but be notice that above method only skip rdb stream. 

method 2.
if redis master has another slave. you can get that salve's `master_replid` and `master_repl_offset`
```
127.0.0.1:6379> info replication
# Replication
role:master
connected_slaves:1
slave0:ip=127.0.0.1,port=62744,state=online,offset=28,lag=1
master_failover_state:no-failover
master_replid:00874914772af73821a6c0b5470d5bc85a94e867
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:28
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:1
repl_backlog_histlen:28
```
you can use `00874914772af73821a6c0b5470d5bc85a94e867` and offset `28` to ignore rdb stream
```
final Replicator replicator = new RedisReplicator("redis://127.0.0.1:6379?replId=00874914772af73821a6c0b5470d5bc85a94e867&replOffset=28");
        replicator.addEventListener(new EventListener() {
            @Override
            public void onEvent(Replicator replicator, Event event) {
                System.out.println(event);
            }
        });

        replicator.open();
```

redis 7.0 
you can use `Configuration.setReplFilters(AOF)` that truely ignore rdb stream only accept aof stream.

**Comment by dnlixiaoxin** [comment]
thanks，this very useful to me
