### ISSUE TITLE
关于从inputStream()读取命令的代码

### ISSUE THREAD

**Issue by BozhongWei** [leonchen83/redis-replicator#57]
前辈您好，最近在学习您写的这个轮子.

请问ReplyPraser.prase()中的代码（那个大while循环），就是将Redis发送过来的命令转换成具体的byte[][]格式的代码，有没有相关协议的参考资料。

想把这一块弄清楚一点，但是网上找不到Redis命令传播阶段发送的内容是以什么格式编排的，如果可以的话希望您可以指点一下，万分感谢！！！

**Comment by leonchen83** [comment]
see [RESP protocol spec](https://redis.io/docs/reference/protocol-spec/)

**Comment by BozhongWei** [comment]
> see [RESP protocol spec](https://redis.io/docs/reference/protocol-spec/)

谢谢！
