### ISSUE TITLE
做两个集群间的持续同步复制(用于多活)是否可行，是否有考虑主备切换，offset点位错乱的问题 

### ISSUE THREAD

**Issue by iNanos** [leonchen83/redis-replicator#74]
最近在寻找一款redis同步工具，验证了redis-shake，将集群A的数据持续同步到集群B，当集群A和B不发生状态变化的时候工作良好，但当集群A发生了主备切换，会出现两个问题，

redis-shake 无法主动获取集群A的新节点拓扑
获取到新master之后，如何与集群B 对账

我想问 redis-replicator 
做两个集群间的持续同步复制(用于多活)是否可行，是否有考虑主备切换，offset点位错乱的问题

**Comment by leonchen83** [comment]
多活和识别主备切换需要用户自己写相关的代码，redis-replicator实现了同步协议，并且可以按照offset点同步数据，以及完善的断线重连机制
